name: my-app

services:
  app:
    build:
      context: ..
      dockerfile: 30_Docker/Dockerfile
    image: my-app-dev:latest
    working_dir: /app
    volumes:
      - ..:/app
    command: python -m my_app

